# Generated by Django 3.2.9 on 2021-11-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live_stream',
            fields=[
                ('live_stream', models.IntegerField(primary_key=True, serialize=False)),
                ('ivs_arn', models.CharField(max_length=255, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, "Live streaming hasn't started yet"), (1, 'Live streaming started'), (2, 'Live ')])),
                ('host_user_id', models.IntegerField()),
                ('performance_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('ingest_endpoints', models.CharField(max_length=255)),
                ('stream_key', models.CharField(max_length=255)),
                ('playback_url', models.CharField(max_length=255)),
                ('comment_available_flag', models.SmallIntegerField(choices=[(0, 'Not available'), (1, 'Available')])),
                ('tipping_available_flag', models.SmallIntegerField(choices=[(0, 'Not available'), (1, 'Available')])),
                ('stamps_granted', models.DecimalField(decimal_places=0, max_digits=15)),
                ('release_datetime', models.DateTimeField(auto_now_add=True)),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(auto_now_add=True)),
                ('total_number_of_viewers', models.IntegerField(null=True)),
                ('seconds_delivered', models.DecimalField(decimal_places=0, max_digits=15)),
                ('chanel_id_sd', models.CharField(max_length=255, null=True)),
                ('chanel_id_fhd', models.CharField(max_length=255, null=True)),
                ('input_id_sd', models.CharField(max_length=255, null=True)),
                ('input_id_fhd', models.CharField(max_length=255, null=True)),
                ('video_url_sd', models.CharField(max_length=255, null=True)),
                ('video_url_fhd', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Live_stream_viewer',
            fields=[
                ('live_stream_id', models.IntegerField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
