# Generated by Django 3.2.9 on 2021-11-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box_notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_read', models.SmallIntegerField(choices=[(0, 'Not read'), (1, 'Read')], default=1)),
                ('read_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box_notification_master_content',
            fields=[
                ('Box_notification_master_content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timing_type', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('memo', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box_notification_trans_content',
            fields=[
                ('box_notification_trans_content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_type', models.IntegerField(choices=[(1, 'Host user'), (2, 'Client user (Mgmt portal user)'), (3, 'System admin user( Mgmt portal user)')], default=1)),
                ('from_user_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_user_ids', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.IntegerField(choices=[(0, 'Not delivered'), (1, 'Delivered')])),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Live stream event'), (2, 'Office event')])),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_private', models.IntegerField(choices=[(0, 'Not private'), (1, 'Private')], default=1)),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('is_archived', models.IntegerField(choices=[(0, 'Not archived'), (1, 'Archived')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('gift_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('points_spent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('image_url', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gift_purchase_history',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points_spent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gift_tipping_history',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points_equivalent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('tipped_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('streaming_method', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField(null=True)),
                ('ticket_available_flag', models.SmallIntegerField(choices=[(0, 'Not available'), (1, 'Available')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('ranking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(1, 'Tipping'), (2, 'Tipped')], default=1)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stamps_code',
            fields=[
                ('stamp_code_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('stamps_granted', models.DecimalField(decimal_places=0, max_digits=15)),
                ('number_of_applicable_user', models.IntegerField(null=True)),
                ('number_of_applied_user', models.IntegerField()),
                ('expires_in', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('points_required', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('expiration_datetime', models.DateTimeField(auto_now_add=True)),
                ('drawing_flag', models.SmallIntegerField(choices=[(0, 'No drawing'), (1, 'By drawing')], default=1)),
                ('drawing_application_deadline', models.DateTimeField(auto_now_add=True, null=True)),
                ('drawing_status', models.SmallIntegerField(choices=[(0, 'Drawing preiod'), (1, ' Purchase method')], default=1)),
                ('stamp_available_flag', models.SmallIntegerField(choices=[(0, 'Not available'), (1, 'Available')], default=1)),
                ('max_number_of_ticket', models.IntegerField()),
                ('number_of_issued_tickets', models.IntegerField()),
                ('is_seat_id_assigned', models.SmallIntegerField(choices=[(0, 'Not assigned'), (1, 'Assigned')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_purchase_history',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('point_amount', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('payment_type', models.CharField(choices=[('card', 'Credit card'), ('cvs', 'Convenience store payment')], max_length=25, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('settle_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('receipt_number', models.CharField(max_length=32, null=True)),
                ('haraikomi_url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_purchase_revervation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('number_of_tickets', models.IntegerField()),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('is_purchased', models.SmallIntegerField(choices=[(0, 'Not purchased'), (1, 'Purchased')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_gift',
            fields=[
                ('user_gift_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Unused'), (1, 'Used')], default=1)),
                ('used_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_point',
            fields=[
                ('user_point_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal')], default=1)),
                ('deposit_reason', models.IntegerField(choices=[(1, 'Purchase')], null=True)),
                ('withdrawal_reason', models.IntegerField(choices=[(1, 'Exchange for a gift'), (2, 'Exchange for a ticket')], null=True)),
                ('points', models.DecimalField(decimal_places=0, max_digits=15)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('points_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_ticket',
            fields=[
                ('user_ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('ticket_id', models.IntegerField()),
                ('is_settled', models.IntegerField(choices=[(0, 'Unsettled'), (1, 'Settled')], default=1)),
                ('seat_id', models.CharField(max_length=255, null=True)),
                ('expire_in', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Unused'), (1, 'Used')], default=1)),
                ('used_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
