# Generated by Django 3.2.9 on 2021-11-11 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_point',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
        migrations.AddField(
            model_name='user_gift',
            name='gift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.gift'),
        ),
        migrations.AddField(
            model_name='user_gift',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
        migrations.AddField(
            model_name='ticket_purchase_revervation',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.ticket'),
        ),
        migrations.AddField(
            model_name='ticket_purchase_revervation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
        migrations.AddField(
            model_name='ticket_purchase_history',
            name='user_ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.user_ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='performance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.performance'),
        ),
        migrations.AddField(
            model_name='stamps_code',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='performance',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.events'),
        ),
        migrations.AddField(
            model_name='gift_tipping_history',
            name='to_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.box_notification_trans_content'),
        ),
        migrations.AddField(
            model_name='gift_tipping_history',
            name='user_gift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.user_gift'),
        ),
        migrations.AddField(
            model_name='gift_purchase_history',
            name='user_gift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.user_gift'),
        ),
        migrations.AddField(
            model_name='gift_purchase_history',
            name='user_point_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.user_point'),
        ),
        migrations.AddField(
            model_name='gift',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='events',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='event_authorized_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
        migrations.AddField(
            model_name='email_notification_trans_content',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='email_notification_master_content',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='box_notification_trans_content',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='box_notification_master_content',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='box_notification',
            name='box_notification_master_content_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Event.box_notification_master_content'),
        ),
        migrations.AddField(
            model_name='box_notification',
            name='box_notification_trans_content_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Event.box_notification_trans_content'),
        ),
        migrations.AddField(
            model_name='box_notification',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
    ]
