# Generated by Django 3.2.9 on 2021-11-12 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='Event.event'),
        ),
    ]
