# Generated by Django 3.2.9 on 2021-11-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_profile_item',
            fields=[
                ('additional_profile_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box_notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.SmallIntegerField(choices=[(0, 'Not read'), (1, 'Read')], default=1)),
                ('read_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box_notification_master_content',
            fields=[
                ('box_notification_master_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('timing_type', models.SmallIntegerField(choices=[(99, 'Any timing')], default=99)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('memo', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box_notification_trans_content',
            fields=[
                ('box_notification_trans_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_type', models.IntegerField(choices=[(1, 'Host user'), (2, 'Client user (Mgmt portal user)'), (3, 'System admin user( Mgmt portal user)')], default=1)),
                ('from_user_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_user_ids', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.IntegerField(choices=[(0, 'Not delivered'), (1, 'Delivered')])),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device_token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.SmallIntegerField(choices=[(1, 'IOS'), (2, 'Android')], default=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=255)),
                ('invalidated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_auth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'General user'), (2, 'Host user'), (3, 'Mgmt portal user')], default=1)),
                ('email', models.CharField(max_length=254)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('to_email', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('body', models.TextField()),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Not sent'), (1, 'Sent'), (2, 'Error')], default=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_notification_master_content',
            fields=[
                ('email_notification_master_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('timing_type', models.SmallIntegerField(choices=[(1, 'When a drawing winner determined'), (2, 'When tickets purchase is complete'), (99, 'Any timing')], default=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('memo', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_notification_trans_content',
            fields=[
                ('email_notification_trans_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_user_ids', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.SmallIntegerField(choices=[(0, 'Not delivered'), (1, 'Delivered')], default=1)),
                ('delivered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Password_reset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'General user'), (2, 'Host user'), (3, 'Mgmt portal user')], default=1)),
                ('email', models.CharField(max_length=254)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefectures',
            fields=[
                ('prefecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('display_order', models.SmallIntegerField()),
                ('is_default', models.SmallIntegerField(choices=[(0, 'Not default'), (1, 'Default')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Push_notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_platform', models.SmallIntegerField(choices=[(1, 'IOS'), (2, 'Android')], default=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('internal_url', models.CharField(max_length=255, null=True)),
                ('scheduled_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Not sent'), (1, 'Sent')], default=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Push_notification_master_content',
            fields=[
                ('push_notification_master_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('timing_type', models.SmallIntegerField(choices=[(1, 'When a livestream event is created'), (2, 'When an office event is created'), (3, 'When a drawing winner determined'), (4, 'When a livestream starts in 10 minutes'), (5, 'When tickets purchase is complete'), (99, 'Any timing')], default=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('internal_url', models.CharField(max_length=255, null=True)),
                ('memo', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Push_notification_trans_content',
            fields=[
                ('push_notification_trans_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('internal_url', models.CharField(max_length=255, null=True)),
                ('to_user_ids', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.IntegerField(choices=[(0, 'Not delivered'), (1, 'Delivered')])),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refresh_token',
            fields=[
                ('refresh_token_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('mgmt_portal_user_id', models.IntegerField(null=True)),
                ('encrypted_refresh_token', models.CharField(max_length=255)),
                ('expires_in', models.DateTimeField(auto_now_add=True)),
                ('is_blacklisted', models.SmallIntegerField(choices=[(0, 'Not blacklisted'), (2, 'Blacklisted')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Related_link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link_url', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('dir_path', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sent_relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('live_stream_id', models.IntegerField(null=True)),
                ('email_notification_trans_content_id', models.IntegerField(null=True)),
                ('push_notification_trans_content_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stamp_receipt_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('live_stream_id', models.IntegerField(null=True)),
                ('stamp_code_id', models.IntegerField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stamp_spending_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spent_for', models.SmallIntegerField(choices=[(1, 'Ticket')], default=1)),
                ('stamp_code_id', models.IntegerField(null=True)),
                ('spent_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
