# Generated by Django 3.2.9 on 2021-11-11 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('MasterData', '0001_initial'),
        ('Event', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp_spending_history',
            name='user_stamp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_stamp'),
        ),
        migrations.AddField(
            model_name='stamp_receipt_history',
            name='user_stamp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_stamp'),
        ),
        migrations.AddField(
            model_name='related_link',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='ranking_summary',
            name='ranking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.ranking'),
        ),
        migrations.AddField(
            model_name='ranking_summary',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
        migrations.AddField(
            model_name='push_notification_trans_content',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='push_notification_master_content',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.clients'),
        ),
        migrations.AddField(
            model_name='push_notification',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users'),
        ),
    ]
