# Generated by Django 3.2.9 on 2021-11-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent_relation',
            name='event_id',
            field=models.IntegerField(null=True),
        ),
    ]
